### PR TITLE
Link to show only failed tests, pagination for launch, breadcrumbs bug

### PR DESCRIPTION
**Pull request by opishcheiko**
- Initial work for setting resolution (not finished yet, so button is disabled for now)
- Trying to split tests and suites by components to reuse, not succeeding to much
- Link to view only failed tests

Screenshot 2020-05-13 at 19 43 52

- Crapy looking, but working pagination for launches

Screenshot 2020-05-13 at 19 43 40

### CODE REVIEW

**Comment by opishcheiko** [comment]
> Looks good! 💪

I also fixed the breadcrumbs issue with ids we added on Friday. Will wait for you to deploy the backend before merging, I guess?

**Comment by Jnegrier** [comment]
> > Looks good! 💪
> 
> I also fixed the breadcrumbs issue with ids we added on Friday. Will wait for you to deploy the backend before merging, I guess?

Actually... feel free to merge :) our staging environment at http://delta-frontend.herokuapp.com/ is already suffering. I can publish new Docker images with both changes tomorrow, so that will update it in Kubernetes

**Comment by opishcheiko** [comment]
> > > Looks good! 💪
> > 
> > 
> > I also fixed the breadcrumbs issue with ids we added on Friday. Will wait for you to deploy the backend before merging, I guess?
> 
> Actually... feel free to merge :) our staging environment at http://delta-frontend.herokuapp.com/ is already suffering. I can publish new Docker images with both changes tomorrow, so that will update it in Kubernetes

Hopefully it works well.
Why is heroku one not working well?

**Comment by Jnegrier** [comment]
> > > > Looks good! 💪
> > > 
> > > 
> > > I also fixed the breadcrumbs issue with ids we added on Friday. Will wait for you to deploy the backend before merging, I guess?
> > 
> > 
> > Actually... feel free to merge :) our staging environment at http://delta-frontend.herokuapp.com/ is already suffering. I can publish new Docker images with both changes tomorrow, so that will update it in Kubernetes
> 
> Hopefully it works well.
> Why is heroku one not working well? In general would be good to have that staging working, but I guess it's not a priority atm

Looks like we are sending project_id is as `undefined` when loading the launches:

Core Logs:
```
020-05-18T08:50:43.276150+00:00 heroku[router]: at=info method=GET path="/api/v1/launch/project/undefined" host=delta-core.herokuapp.com request_id=8472424d-96a8-4771-9aa9-0928ed7dac70 fwd="3.85.142.40" dyno=web.1 connect=1ms service=2ms status=404 bytes=210 protocol=https

2020-05-18T08:50:43.263145+00:00 app[web.1]: 10.71.199.143 - - [18/May/2020:08:50:43 +0000] "GET /api/v1/launch/project/undefined HTTP/1.1" 404 51 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
```

Frontend Logs:

```
2020-05-18T08:50:43.331190+00:00 heroku[router]: at=info method=GET path="/launches/undefined" host=delta-frontend.herokuapp.com request_id=032bcf15-e1a8-439b-86ee-1820862e7d08 fwd="37.228.251.5" dyno=web.1 connect=0ms service=73ms status=500 bytes=6160 protocol=https

2020-05-18T08:50:43.280860+00:00 app[web.1]: TypeError: props.launches.slice is not a function

2020-05-18T08:50:43.280870+00:00 app[web.1]:     at Launches (/app/.next/serverless/pages/launches/[launchesByProjectId].js:190054:42)

2020-05-18T08:50:43.280870+00:00 app[web.1]:     at d (/app/.next/serverless/pages/launches/[launchesByProjectId].js:55332:498)

2020-05-18T08:50:43.280871+00:00 app[web.1]:     at $a (/app/.next/serverless/pages/launches/[launchesByProjectId].js:55335:16)

2020-05-18T08:50:43.280871+00:00 app[web.1]:     at a.b.render (/app/.next/serverless/pages/launches/[launchesByProjectId].js:55340:476)

2020-05-18T08:50:43.280872+00:00 app[web.1]:     at a.b.read (/app/.next/serverless/pages/launches/[launchesByProjectId].js:55340:18)

2020-05-18T08:50:43.280872+00:00 app[web.1]:     at renderToString (/app/.next/serverless/pages/launches/[launchesByProjectId].js:55350:364)

2020-05-18T08:50:43.280872+00:00 app[web.1]:     at render (/app/.next/serverless/pages/launches/[launchesByProjectId].js:5333:16)

2020-05-18T08:50:43.280872+00:00 app[web.1]:     at renderPage (/app/.next/serverless/pages/launches/[launchesByProjectId].js:5655:16)

2020-05-18T08:50:43.280873+00:00 app[web.1]:     at Object.ctx.renderPage (/app/.next/serverless/pages/launches/[launchesByProjectId].js:157649:26)

2020-05-18T08:50:43.280874+00:00 app[web.1]:     at Function.getInitialProps (/app/.next/serverless/pages/launches/[launchesByProjectId].js:147629:19)
```

**Pull request merged**
