### PR TITLE
Adding test type buttons for the launch, test stats for the suite

### PR DESCRIPTION
**Pull request by opishcheiko**
Test version to see if it's usable/makes sense.

Buttons  on the launch to go directly to the test suite: Screenshot 2020-05-22 at 23 21 01

Number of failed/passed tests on the suite level: Screenshot 2020-05-23 at 00 17 08

### CODE REVIEW

**Comment by Jnegrier** [comment]
Hey @opishcheiko I was just trying this branch locally and looks like there is problem in the backend, with the `api/v1/launch/project/` endpoint, looks like the endpoint is returning just one of the tesruns...

Here for the launch 17, we should return data for test runs 18 and 20...

Screenshot 2020-05-23 at 11 45 50

But instead, we are just returning test run 18

Screenshot 2020-05-23 at 11 45 22

I'll take a look at it today 😃

**Comment by opishcheiko** [comment]
> I'll take a look at it today 😃
Thanks @Jnegrier

**Comment by Jnegrier** [comment]
> > I'll take a look at it today 😃
> > Thanks @Jnegrier

Fixed it, the frontend looks amazing!

Screenshot 2020-05-23 at 12 51 59

Screenshot 2020-05-23 at 12 52 26

Will create the PR for the backend now, thanks @opishcheiko

**Comment by opishcheiko** [comment]
made the rows thiner
Screenshot 2020-05-25 at 09 19 03

**Pull request merged**
