### PR TITLE
Added limit to display and store labels and links

### PR DESCRIPTION
**Pull request by Jnegrier**

### CODE REVIEW

**Comment by opishcheiko** [comment]
do you mind if i add some css to this pr? @Jnegrier

**Comment by Jnegrier** [comment]
> do you mind if i add some css to this pr? @Jnegrier

Not at all, please do 👍

**Comment by opishcheiko** [comment]
Applied some styling. Will be something like this:
Screenshot 2020-12-03 at 19 03 26

**Comment by Jnegrier** [comment]
I cannot approve it cause it's my PR, but I like the changes @opishcheiko 👍

**Pull request merged**
